services:
  php-env:
    build: .
    volumes:
      - ./src:/var/www/html
    command: /bin/sh -c "chmod -R 777 /var/www/html && apache2-foreground"
    ports:
      - "8000:80"
    networks:
      - net-1

  mysql1:
    image: mysql
    environment:
      MYSQL_DATABASE: "dbcoba"
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - /home/naufal/Documents/pemrograman-sisi-server/shop_cart/mysql_data:/var/lib/mysql
    networks:
      - net-1

  phpmyadmin1:
    image: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql1
    networks:
      - net-1

networks:
  net-1:
    driver: bridge
